name: Build

on: [push]

jobs:
  build:
    strategy:
      # Default is true, cancels jobs for other platforms in the matrix if one fails
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        go: [ '1.19', '1.20' ]

        include:
          # Set the minimum Go patch version for the given Go minor
          # Usable via ${{ matrix.GO_SEMVER }}
          - go: '1.19'
            GO_SEMVER: '~1.19.9'

          - go: '1.20'
            GO_SEMVER: '~1.20.4'

          # Set some variables per OS, usable via ${{ matrix.VAR }}
          # CADDY_BIN_PATH: the path to the compiled Caddy binary, for artifact publishing
          # SUCCESS: the typical value for $? per OS (Windows/pwsh returns 'True')
          - os: ubuntu-latest
            CADDY_BIN_PATH: ./cmd/caddy/caddy
            SUCCESS: 0

          - os: macos-latest
            CADDY_BIN_PATH: ./cmd/caddy/caddy
            SUCCESS: 0

          - os: windows-latest
            CADDY_BIN_PATH: ./cmd/caddy/caddy.exe
            SUCCESS: 'True'

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v

      - name: Test Report
        run: go test -v ./... -json > testReport.json

      - name: Test Coverage
        run: go test -v ./... -covermode=atomic -coverprofile=coverage.out
